### ISSUE TITLE
Error when installing extension:  Failed to open stream: ../vendor/autoload.php

### ISSUE THREAD

**Issue by rkilchmn** [saygoweb/frontaccounting-module-sgw_import#1]
Hi,

when installing (not activating) i get these errors:

include_once(/usr/share/webapps/frontaccounting_git/core/modules/frontaccounting-module-sgw_import/vendor/autoload.php): Failed to open stream: No such file or directory in file: /usr/share/webapps/frontaccounting_git/core/modules/frontaccounting-module-sgw_import/hooks.php at line 8

include_once(): Failed opening '/usr/share/webapps/frontaccounting_git/core/modules/frontaccounting-module-sgw_import/vendor/autoload.php' for inclusion (include_path='.:') in file: /usr/share/webapps/frontaccounting_git/core/modules/frontaccounting-module-sgw_import/hooks.php at line 8

seams some files/directory are missing ("vendor")?

Cheers Roger

**Comment by cambell-prince** [comment]
@rkilchmn I've not made a release build of this extension with all the dependencies available.  For development I use `composer` to manage dependencies.  So to get the development version working you need to have [composer](https://getcomposer.org) installed from [https://getcomposer.org](https://getcomposer.org).

Then you run `composer install` in the extension folder and it will create the vendor folder and the file autoload.php for you.

If that's a bridge to far, let me know and I'll make a release version for you to download.

**Comment by cambell-prince** [comment]
I was fixing something anyway, so I made a [release](https://github.com/saygoweb/frontaccounting-module-sgw_import/releases).  It is [release](https://github.com/saygoweb/frontaccounting-module-sgw_import/releases) 1.0.2 and you should be able to download the distribution files (not the source files) and hopefully it should work for you.
